In [35]:
import os
from pathlib import Path

import polars as pl
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np

from simple_evals.improvement.models.results import AllResults
from simple_evals.improvement.models.rag_logs import RAGLog
from simple_evals.improvement.paths import RESULTS_DIR

Columns we need:
- prompt_id
- similarity_score
- theme
- effect_of_rag

In [11]:
train_test = pl.read_csv("train_test.csv")

In [3]:
baseline_results_path = RESULTS_DIR / (
    "5df4ba309cb03369f6663786ae6a9904385524a9/"
    + "maverick/healthbench_llama-4-maverick_20251023_212754_allresults.json"
)
baseline_results = AllResults.from_file(baseline_results_path)

In [4]:
rag_run_dir = (
    RESULTS_DIR / "cbd99b81af7e1cb59d122dec8d0cb78717b8d10d/llama-4-maverick-rag2"
)
rag_results_path = (
    rag_run_dir / "healthbench_llama-4-maverick-rag2_20251120_175439_allresults.json"
)
rag_logs_dir = rag_run_dir / "rag_info"
rag_results = AllResults.from_file(rag_results_path)
rag_logs = RAGLog.from_log_dir(rag_logs_dir)

In [5]:
def flatten_metadata(results: AllResults, model_name: str) -> list[dict]:
    """
    Flattens the 'example_level_metadata' objects from the benchmark results file.
    """
    out = []
    for metadata in results.metadata.example_level_metadata:
        out.append(
            {
                "prompt_id": metadata.prompt_id,
                f"score_{model_name}": metadata.score,
            }
        )
    return out


def flatten_rag_logs(rag_logs: list[RAGLog]) -> list[dict]:
    """
    Flattens the rag_logs into dictionaries. It does this by leaving off the
    "conversations" key.
    """
    out = []
    for log in rag_logs:
        out.append(
            {
                "prompt_id": log.prompt_id,
                "vector_search_row_id": log.vector_search_row_id,
                "atropos_case_id": log.atropos_case_id,
                "similarity_score": log.similarity_score,
            }
        )
    return out

In [6]:
baseline = pl.DataFrame(flatten_metadata(baseline_results, "baseline"))
rag = pl.DataFrame(flatten_metadata(rag_results, "rag"))
rag_logs_df = pl.DataFrame(flatten_rag_logs(rag_logs))

In [12]:
combined = (
    baseline.join(rag, on="prompt_id")
    .join(rag_logs_df, on="prompt_id")
    .join(train_test, on="prompt_id")
)
combined.head()

shape: (5, 8)
┌────────────┬────────────┬───────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ prompt_id  ┆ score_base ┆ score_rag ┆ vector_sea ┆ atropos_c ┆ similarit ┆ theme     ┆ train_tes │
│ ---        ┆ line       ┆ ---       ┆ rch_row_id ┆ ase_id    ┆ y_score   ┆ ---       ┆ t         │
│ str        ┆ ---        ┆ f64       ┆ ---        ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│            ┆ f64        ┆           ┆ f64        ┆ str       ┆ f64       ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1f548d5b-c ┆ 0.637363   ┆ 0.483516  ┆ 8431.0     ┆ ea4beae57 ┆ 0.003307  ┆ context_s ┆ train     │
│ d00-49a0-b ┆            ┆           ┆            ┆ e894b2da1 ┆           ┆ eeking    ┆           │
│ 327-283a2e ┆            ┆           ┆            ┆ 57caa657c ┆           ┆           ┆           │
│ …          ┆            ┆           ┆            ┆ c5b…      ┆           ┆           ┆           │
│ 0b8f1d60-2 ┆ 0.338983   ┆ 0.237288  ┆ 1401.0     ┆ 25206c98a ┆ 0.002424  ┆ communica ┆ test      │
│ 081-4562-9 ┆            ┆           ┆            ┆ 3ca4ce594 ┆           ┆ tion      ┆           │
│ 8f7-b6a976 ┆            ┆           ┆            ┆ 365ff1664 ┆           ┆           ┆           │
│ …          ┆            ┆           ┆            ┆ ecc…      ┆           ┆           ┆           │
│ 6f7a2ee9-e ┆ 1.0        ┆ 1.0       ┆ 8551.0     ┆ dc800050b ┆ 0.002118  ┆ emergency ┆ test      │
│ 9c6-42d8-b ┆            ┆           ┆            ┆ 3f04b1bb1 ┆           ┆ _referral ┆           │
│ 79f-22dea9 ┆            ┆           ┆            ┆ 9a94aff5d ┆           ┆ s         ┆           │
│ …          ┆            ┆           ┆            ┆ a21…      ┆           ┆           ┆           │
│ 19ec4833-8 ┆ 0.469136   ┆ 0.37037   ┆ 39.0       ┆ c86238f20 ┆ 0.002118  ┆ hedging   ┆ test      │
│ 6e9-4166-8 ┆            ┆           ┆            ┆ fed43c9be ┆           ┆           ┆           │
│ b82-d1da09 ┆            ┆           ┆            ┆ a953bd2c2 ┆           ┆           ┆           │
│ …          ┆            ┆           ┆            ┆ b19…      ┆           ┆           ┆           │
│ 7ebc830a-8 ┆ 0.257143   ┆ 0.1       ┆ 3925.0     ┆ 11a057dc3 ┆ 0.001943  ┆ emergency ┆ test      │
│ dbd-489b-9 ┆            ┆           ┆            ┆ ae4482094 ┆           ┆ _referral ┆           │
│ d61-4d8bac ┆            ┆           ┆            ┆ b98653e1b ┆           ┆ s         ┆           │
│ …          ┆            ┆           ┆            ┆ 052…      ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [15]:
diffs = combined.with_columns(
    # Calculate the difference between the runs for each question
    (pl.col("score_rag") - pl.col("score_baseline")).alias("effect_of_rag"),
    # Calculate the difference between the runs for each question
    (
        pl.when((pl.col("score_rag") - pl.col("score_baseline") > 0))
        .then(pl.lit("better"))
        .otherwise(pl.lit("worse"))
    ).alias("better_or_worse"),
).filter(pl.col("train_test") == "train")

In [16]:
diffs

shape: (2_500, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ prompt_id ┆ score_bas ┆ score_rag ┆ vector_se ┆ … ┆ theme     ┆ train_tes ┆ effect_of ┆ better_o │
│ ---       ┆ eline     ┆ ---       ┆ arch_row_ ┆   ┆ ---       ┆ t         ┆ _rag      ┆ r_worse  │
│ str       ┆ ---       ┆ f64       ┆ id        ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆           ┆ ---       ┆   ┆           ┆ str       ┆ f64       ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1f548d5b- ┆ 0.637363  ┆ 0.483516  ┆ 8431.0    ┆ … ┆ context_s ┆ train     ┆ -0.153846 ┆ worse    │
│ cd00-49a0 ┆           ┆           ┆           ┆   ┆ eeking    ┆           ┆           ┆          │
│ -b327-283 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a2e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c971f9d1- ┆ 0.245614  ┆ 0.0       ┆ 906.0     ┆ … ┆ global_he ┆ train     ┆ -0.245614 ┆ worse    │
│ 5f6a-464e ┆           ┆           ┆           ┆   ┆ alth      ┆           ┆           ┆          │
│ -b282-41c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8f0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5a6e4a41- ┆ 0.086957  ┆ 0.130435  ┆ 4635.0    ┆ … ┆ global_he ┆ train     ┆ 0.043478  ┆ better   │
│ 3ea6-4050 ┆           ┆           ┆           ┆   ┆ alth      ┆           ┆           ┆          │
│ -a971-934 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 33f…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8f2a65de- ┆ -0.119403 ┆ -0.119403 ┆ 7847.0    ┆ … ┆ global_he ┆ train     ┆ 0.0       ┆ worse    │
│ dea7-48e8 ┆           ┆           ┆           ┆   ┆ alth      ┆           ┆           ┆          │
│ -8adb-619 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4ec…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6d5f483c- ┆ 0.048276  ┆ 0.213793  ┆ 308.0     ┆ … ┆ global_he ┆ train     ┆ 0.165517  ┆ better   │
│ 3e86-456d ┆           ┆           ┆           ┆   ┆ alth      ┆           ┆           ┆          │
│ -bfd5-4e2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8de…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6c1eaabb- ┆ 1.0       ┆ 0.558824  ┆ 435.0     ┆ … ┆ health_da ┆ train     ┆ -0.441176 ┆ worse    │
│ 908a-4414 ┆           ┆           ┆           ┆   ┆ ta_tasks  ┆           ┆           ┆          │
│ -8d73-597 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b53…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4d8b028- ┆ -0.692308 ┆ 0.461538  ┆ 10755.0   ┆ … ┆ health_da ┆ train     ┆ 1.153846  ┆ better   │
│ f148-47ca ┆           ┆           ┆           ┆   ┆ ta_tasks  ┆           ┆           ┆          │
│ -b1bc-c5c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 467…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0175eaea- ┆ 0.388889  ┆ -0.111111 ┆ 7965.0    ┆ … ┆ communica ┆ train     ┆ -0.5      ┆ worse    │
│ 4d14-4932 ┆           ┆           ┆           ┆   ┆ tion      ┆           ┆           ┆          │
│ -956b-601 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 951…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a644d818- ┆ 0.411765  ┆ 0.117647  ┆ 1556.0    ┆ … ┆ communica ┆ train     ┆ -0.294118 ┆ worse    │
│ 6989-42b4 ┆           ┆           ┆           ┆   ┆ tion      ┆           ┆           ┆          │
│ -84b7-f87 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ff1…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e1cf80cd- ┆ 0.392405  ┆ 0.455696  ┆ 10444.0   ┆ … ┆ emergency ┆ train     ┆ 0.063291  ┆ better   │
│ 965e-4a64 ┆           ┆           ┆           ┆   ┆ _referral ┆           ┆           ┆          │
│ -b2e3-a95 ┆           ┆           ┆           ┆   ┆ s         ┆           ┆           ┆          │
│ 497…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# impact code the themes
impact_codes = diffs.group_by("theme").agg(
    pl.col("effect_of_rag").mean().alias("theme_impact_coded")
)
impact_codes

shape: (7, 2)
┌─────────────────────┬────────────────────┐
│ theme               ┆ theme_impact_coded │
│ ---                 ┆ ---                │
│ str                 ┆ f64                │
╞═════════════════════╪════════════════════╡
│ global_health       ┆ -0.06562           │
│ complex_responses   ┆ -0.011168          │
│ emergency_referrals ┆ -0.068764          │
│ health_data_tasks   ┆ -0.00074           │
│ context_seeking     ┆ -0.028737          │
│ hedging             ┆ -0.052157          │
│ communication       ┆ -0.021714          │
└─────────────────────┴────────────────────┘

In [23]:
train_df = diffs.join(impact_codes, on="theme").with_columns(
    pl.when(pl.col("better_or_worse") == "better")
    .then(pl.lit(1))
    .otherwise(pl.lit(0))
    .alias("better_or_worse_binary")
)
train_df

shape: (2_500, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ prompt_id ┆ score_bas ┆ score_rag ┆ vector_se ┆ … ┆ effect_of ┆ better_or ┆ theme_imp ┆ better_o │
│ ---       ┆ eline     ┆ ---       ┆ arch_row_ ┆   ┆ _rag      ┆ _worse    ┆ act_coded ┆ r_worse_ │
│ str       ┆ ---       ┆ f64       ┆ id        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ binary   │
│           ┆ f64       ┆           ┆ ---       ┆   ┆ f64       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1f548d5b- ┆ 0.637363  ┆ 0.483516  ┆ 8431.0    ┆ … ┆ -0.153846 ┆ worse     ┆ -0.028737 ┆ 0        │
│ cd00-49a0 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b327-283 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a2e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c971f9d1- ┆ 0.245614  ┆ 0.0       ┆ 906.0     ┆ … ┆ -0.245614 ┆ worse     ┆ -0.06562  ┆ 0        │
│ 5f6a-464e ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b282-41c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8f0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5a6e4a41- ┆ 0.086957  ┆ 0.130435  ┆ 4635.0    ┆ … ┆ 0.043478  ┆ better    ┆ -0.06562  ┆ 1        │
│ 3ea6-4050 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -a971-934 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 33f…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8f2a65de- ┆ -0.119403 ┆ -0.119403 ┆ 7847.0    ┆ … ┆ 0.0       ┆ worse     ┆ -0.06562  ┆ 0        │
│ dea7-48e8 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8adb-619 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4ec…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6d5f483c- ┆ 0.048276  ┆ 0.213793  ┆ 308.0     ┆ … ┆ 0.165517  ┆ better    ┆ -0.06562  ┆ 1        │
│ 3e86-456d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -bfd5-4e2 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 8de…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6c1eaabb- ┆ 1.0       ┆ 0.558824  ┆ 435.0     ┆ … ┆ -0.441176 ┆ worse     ┆ -0.00074  ┆ 0        │
│ 908a-4414 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8d73-597 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b53…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4d8b028- ┆ -0.692308 ┆ 0.461538  ┆ 10755.0   ┆ … ┆ 1.153846  ┆ better    ┆ -0.00074  ┆ 1        │
│ f148-47ca ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b1bc-c5c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 467…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0175eaea- ┆ 0.388889  ┆ -0.111111 ┆ 7965.0    ┆ … ┆ -0.5      ┆ worse     ┆ -0.021714 ┆ 0        │
│ 4d14-4932 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -956b-601 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 951…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a644d818- ┆ 0.411765  ┆ 0.117647  ┆ 1556.0    ┆ … ┆ -0.294118 ┆ worse     ┆ -0.021714 ┆ 0        │
│ 6989-42b4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -84b7-f87 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ff1…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e1cf80cd- ┆ 0.392405  ┆ 0.455696  ┆ 10444.0   ┆ … ┆ 0.063291  ┆ better    ┆ -0.068764 ┆ 1        │
│ 965e-4a64 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b2e3-a95 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 497…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
train_df.select(
    "similarity_score", "theme_impact_coded", "better_or_worse_binary"
).describe()

shape: (9, 4)
┌────────────┬──────────────────┬────────────────────┬────────────────────────┐
│ statistic  ┆ similarity_score ┆ theme_impact_coded ┆ better_or_worse_binary │
│ ---        ┆ ---              ┆ ---                ┆ ---                    │
│ str        ┆ f64              ┆ f64                ┆ f64                    │
╞════════════╪══════════════════╪════════════════════╪════════════════════════╡
│ count      ┆ 2500.0           ┆ 2500.0             ┆ 2500.0                 │
│ null_count ┆ 0.0              ┆ 0.0                ┆ 0.0                    │
│ mean       ┆ 0.002181         ┆ -0.040497          ┆ 0.3136                 │
│ std        ┆ 0.000441         ┆ 0.023208           ┆ 0.464049               │
│ min        ┆ 0.001379         ┆ -0.068764          ┆ 0.0                    │
│ 25%        ┆ 0.001861         ┆ -0.06562           ┆ 0.0                    │
│ 50%        ┆ 0.002088         ┆ -0.052157          ┆ 0.0                    │
│ 75%        ┆ 0.002406         ┆ -0.021714          ┆ 1.0                    │
│ max        ┆ 0.004808         ┆ -0.00074           ┆ 1.0                    │
└────────────┴──────────────────┴────────────────────┴────────────────────────┘

In [ ]:
model = RandomForestClassifier(random_state=42)
aucs = cross_val_score(
    model,
    X=train_df.select("similarity_score", "theme_impact_coded").to_numpy(),
    y=train_df["better_or_worse_binary"].to_numpy(),
    cv=10,
    scoring="roc_auc",
)

In [ ]:
aucs

array([0.56436345, 0.55403995, 0.51229875, 0.52817531, 0.51073345,
       0.45087955, 0.50862388, 0.48201199, 0.47494263, 0.50281294])

In [ ]:
np.mean(aucs)

np.float64(0.5088881901895126)